[package]
publish = false
name = "main"
version = "0.0.1"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
csv = "1.3.1"

[[bin]]
name = "main"
path = "main.rs"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
