[package]
publish = false
name = "main"
version = "0.0.1"
edition = "2021"

[workspace]

[dependencies]
simd-csv = {path = "../../../"}

[[bin]]
name = "main"
path = "main.rs"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
